-- ..:: CASO 1 ::..

-- Elimina primero las tablas dependientes
DROP TABLE DETALLE_SERVICIO CASCADE CONSTRAINTS;
DROP TABLE MANTENCION CASCADE CONSTRAINTS;
DROP TABLE ESTANDAR CASCADE CONSTRAINTS;
DROP TABLE PREMIUM CASCADE CONSTRAINTS;
DROP TABLE AUTOMOVIL CASCADE CONSTRAINTS;
DROP TABLE SERVICIO CASCADE CONSTRAINTS;
DROP TABLE MECANICO CASCADE CONSTRAINTS;

-- Luego las tablas fuertes
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TIPO_AUTOMOVIL CASCADE CONSTRAINTS;
DROP TABLE MODELO CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;

-- PAIS
CREATE TABLE PAIS (
    id_pais NUMBER(3) GENERATED ALWAYS AS IDENTITY
        (START WITH 9 INCREMENT BY 3),
    nom_pais VARCHAR2(30) NOT NULL,
    CONSTRAINT PAIS_PK PRIMARY KEY (id_pais)
);

-- CIUDAD
CREATE TABLE CIUDAD (
    id_ciudad NUMBER(3),
    nom_ciudad VARCHAR2(30) NOT NULL,
    cod_pais NUMBER(3) NOT NULL,
    CONSTRAINT CIUDAD_PK PRIMARY KEY (id_ciudad),
    CONSTRAINT CIUDAD_FK_PAIS FOREIGN KEY (cod_pais) REFERENCES PAIS(id_pais)
);

-- SUCURSAL
CREATE TABLE SUCURSAL (
    id_sucursal CHAR(3),
    nom_sucursal VARCHAR2(20) NOT NULL,
    calle VARCHAR2(20),
    num_calle NUMBER(4),
    cod_ciudad NUMBER(3) NOT NULL,
    CONSTRAINT SUCURSAL_PK PRIMARY KEY (id_sucursal),
    CONSTRAINT SUCURSAL_FK_CIUDAD FOREIGN KEY (cod_ciudad) REFERENCES CIUDAD(id_ciudad)
);

-- MARCA
CREATE TABLE MARCA (
    id_marca NUMBER(2),
    descripcion VARCHAR2(20) NOT NULL,
    CONSTRAINT MARCA_PK PRIMARY KEY (id_marca)
);

-- MODELO
CREATE TABLE MODELO (
    id_modelo NUMBER(5),
    marca_id NUMBER(2) NOT NULL,
    descripcion VARCHAR2(20) NOT NULL,
    CONSTRAINT MODELO_PK PRIMARY KEY (id_modelo, marca_id),
    CONSTRAINT MODELO_FK_MARCA FOREIGN KEY (marca_id) REFERENCES MARCA(id_marca)
);

-- TIPO_AUTOMOVIL
CREATE TABLE TIPO_AUTOMOVIL (
    id_tipo CHAR(3),
    descripcion VARCHAR2(20) NOT NULL,
    CONSTRAINT TIPO_AUTOMOVIL_PK PRIMARY KEY (id_tipo)
);

-- CLIENTE
CREATE TABLE CLIENTE (
    rut NUMBER(8),
    dv CHAR(1) NOT NULL,
    pnombre VARCHAR2(20),
    snombre VARCHAR2(20),
    apat VARCHAR2(20),
    amat VARCHAR2(20),
    telefono VARCHAR2(12),
    email VARCHAR2(40),
    tipo_cl CHAR(1),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (rut),
    CONSTRAINT CLIENTE_CK_TIPO CHECK (tipo_cl IN ('E','P'))
);

-- AUTOMOVIL
CREATE TABLE AUTOMOVIL (
    patente CHAR(8),
    anio NUMBER(4),
    cant_puertas NUMBER(1),
    km NUMBER(6),
    color VARCHAR2(10),
    cod_tipo_auto CHAR(3) NOT NULL,
    cod_modelo NUMBER(5) NOT NULL,
    cod_marca NUMBER(2) NOT NULL,
    cl_rut NUMBER(8) NOT NULL,
    CONSTRAINT AUTOMOVIL_PK PRIMARY KEY (patente),
    CONSTRAINT AUTOMOVIL_FK_TIPO FOREIGN KEY (cod_tipo_auto) REFERENCES TIPO_AUTOMOVIL(id_tipo),
    CONSTRAINT AUTOMOVIL_FK_MODELO FOREIGN KEY (cod_modelo, cod_marca) REFERENCES MODELO(id_modelo, marca_id),
    CONSTRAINT AUTOMOVIL_FK_CLIENTE FOREIGN KEY (cl_rut) REFERENCES CLIENTE(rut)
);

-- MECANICO
CREATE TABLE MECANICO (
    cod_mecanico NUMBER(5) GENERATED ALWAYS AS IDENTITY
        (START WITH 460 INCREMENT BY 7),
    pnombre VARCHAR2(20),
    snombre VARCHAR2(20),
    apat VARCHAR2(20),
    amat VARCHAR2(20),
    bono_jefatura NUMBER(10),
    sueldo NUMBER(10),
    monto_impuestos NUMBER(10),
    cod_supervisor NUMBER(5),
    CONSTRAINT MECANICO_PK PRIMARY KEY (cod_mecanico),
    CONSTRAINT MECANICO_FK_SUPERVISOR FOREIGN KEY (cod_supervisor) REFERENCES MECANICO(cod_mecanico)
);

-- SERVICIO
CREATE TABLE SERVICIO (
    id_servicio NUMBER(3),
    descripcion VARCHAR2(100),
    costo NUMBER(7),
    CONSTRAINT SERVICIO_PK PRIMARY KEY (id_servicio)
);

-- MANTENCION
CREATE TABLE MANTENCION (
    num_mantencion NUMBER(4),
    cod_sucursal CHAR(3) NOT NULL,
    fecha_ingreso DATE,
    fecha_salida DATE,
    patente_auto CHAR(8) NOT NULL,
    cod_mecanico NUMBER(5) NOT NULL,
    costo_total NUMBER(7),
    estado VARCHAR2(15),
    CONSTRAINT MANTENCION_PK PRIMARY KEY (num_mantencion),
    CONSTRAINT MANT_FK_AUTOMOVIL FOREIGN KEY (patente_auto) REFERENCES AUTOMOVIL(patente),
    CONSTRAINT MANT_FK_MECANICO FOREIGN KEY (cod_mecanico) REFERENCES MECANICO(cod_mecanico),
    CONSTRAINT MANT_FK_SUCURSAL FOREIGN KEY (cod_sucursal) REFERENCES SUCURSAL(id_sucursal)
);

-- DETALLE_SERVICIO
CREATE TABLE DETALLE_SERVICIO (
    mantencion_num NUMBER(4),
    cod_servicio NUMBER(3),
    descuento_serv NUMBER(4,3),
    cantidad NUMBER(3),
    CONSTRAINT DETALLE_SERVICIO_PK PRIMARY KEY (mantencion_num, cod_servicio),
    CONSTRAINT DET_SERV_FK_MANTENCION FOREIGN KEY (mantencion_num) REFERENCES MANTENCION(num_mantencion),
    CONSTRAINT DET_SERV_FK_SERVICIO FOREIGN KEY (cod_servicio) REFERENCES SERVICIO(id_servicio)
);

-- ESTANDAR
CREATE TABLE ESTANDAR (
    cl_rut NUMBER(8),
    puntaje_fidelidad NUMBER(10),
    CONSTRAINT ESTANDAR_PK PRIMARY KEY (cl_rut),
    CONSTRAINT ESTANDAR_FK_CLIENTE FOREIGN KEY (cl_rut) REFERENCES CLIENTE(rut)
);

-- PREMIUM
CREATE TABLE PREMIUM (
    cl_rut NUMBER(8),
    pesos_clientes NUMBER(10),
    monto_credito NUMBER(10),
    CONSTRAINT PREMIUM_PK PRIMARY KEY (cl_rut),
    CONSTRAINT PREMIUM_FK_CLIENTE FOREIGN KEY (cl_rut) REFERENCES CLIENTE(rut)
);

-- ..:: CASO 2 ::..

